package org.jbserv.mail.imap.command;

public enum CommandType {

	APPEND, AUTHENTICATE, CAPABILITY, CHECK, CLOSE, COPY, CREATE, DELETE, EXAMINE, EXPUNGE, FETCH, LIST, LOGIN, LOGOUT, LSUB, NOOP, RENAME, SEARCH, SELECT, STARTTLS, STATUS, STORE, SUBSCRIBE, UID, UNSUBSCRIBE;

}
